/** @jsxImportSource react */
import RootLayout from '../layouts/RootLayout';

export const metadata = {
  title: 'Welcome to blog-web',
  description: 'Generated by create-nx-workspace',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id">
      <head></head>
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
